version: '1' #docker compose verison
services:
  redis-server:
    image: 'redis' #get from dockerhub
  node-app:
    restart: always
    volumes:
      - ./server:/app
    build: 
      context: ./server
      dockerfile: Dockerfile.dev
    ports: #docker port mapping
      - "4001:8081"