version: '1' #docker compose verison
services:
  postgres:
    image: 'postgres:latest'
    environment:
      POSTGRES_PASSWORD: example
  server:
    restart: always
    volumes:
      - ./server:/app
    build: 
      context: ./server
      dockerfile: Dockerfile.dev
    environment:
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=example
      - PGPORT=5432
    ports:
      - "8081:8081"
  client:
    volumes:
      - ./client:/app
    build: 
      context: ./client
      dockerfile: Dockerfile.dev
    ports: #docker port mapping
      - "4001:3000"